window.env = {
  "MANPATH": "/opt/homebrew/share/man:/usr/share/man:/usr/local/share/man:/opt/homebrew/share/man:",
  "TERM_PROGRAM": "vscode",
  "NODE": "/opt/homebrew/Cellar/node/18.10.0/bin/node",
  "INIT_CWD": "/Users/sanil/Documents/untitled folder/fitness",
  "SHELL": "/bin/zsh",
  "TERM": "xterm-256color",
  "TMPDIR": "/var/folders/rj/27qvmjcs6tdc85zwr8d51j2h0000gn/T/",
  "HOMEBREW_REPOSITORY": "/opt/homebrew",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "npm_config_global_prefix": "/opt/homebrew",
  "TERM_PROGRAM_VERSION": "1.72.1",
  "MallocNanoZone": "0",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "ZDOTDIR": "/Users/sanil",
  "COLOR": "1",
  "npm_config_noproxy": "",
  "npm_config_local_prefix": "/Users/sanil/Documents/untitled folder/fitness",
  "USER": "sanil",
  "COMMAND_MODE": "unix2003",
  "npm_config_globalconfig": "/opt/homebrew/etc/npmrc",
  "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.RHjLQVPbe4/Listeners",
  "__CF_USER_TEXT_ENCODING": "0x1F5:0x0:0x0",
  "npm_execpath": "/Users/sanil/node_modules/npm/bin/npm-cli.js",
  "PATH": "/Users/sanil/Documents/untitled folder/fitness/node_modules/.bin:/Users/sanil/Documents/untitled folder/node_modules/.bin:/Users/sanil/Documents/node_modules/.bin:/Users/sanil/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/Users/sanil/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/Users/sanil/Documents/untitled folder/fitness/node_modules/.bin:/Users/sanil/Documents/untitled folder/node_modules/.bin:/Users/sanil/Documents/node_modules/.bin:/Users/sanil/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/opt/homebrew/sbin",
  "_": "/Users/sanil/Documents/untitled folder/fitness/node_modules/.bin/react-dotenv",
  "npm_package_json": "/Users/sanil/Documents/untitled folder/fitness/package.json",
  "__CFBundleIdentifier": "com.microsoft.VSCode",
  "USER_ZDOTDIR": "/Users/sanil",
  "npm_config_init_module": "/Users/sanil/.npm-init.js",
  "npm_config_userconfig": "/Users/sanil/.npmrc",
  "PWD": "/Users/sanil/Documents/untitled folder/fitness",
  "npm_command": "run-script",
  "EDITOR": "vi",
  "npm_lifecycle_event": "build",
  "LANG": "en_GB.UTF-8",
  "npm_package_name": "fitness_app",
  "XPC_FLAGS": "0x0",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "npm_config_node_gyp": "/Users/sanil/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
  "XPC_SERVICE_NAME": "0",
  "npm_package_version": "0.1.0",
  "VSCODE_INJECTION": "1",
  "HOME": "/Users/sanil",
  "SHLVL": "3",
  "VSCODE_GIT_ASKPASS_MAIN": "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js",
  "HOMEBREW_PREFIX": "/opt/homebrew",
  "LOGNAME": "sanil",
  "npm_config_cache": "/Users/sanil/.npm",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "VSCODE_GIT_IPC_HANDLE": "/var/folders/rj/27qvmjcs6tdc85zwr8d51j2h0000gn/T/vscode-git-34b6579bae.sock",
  "npm_config_user_agent": "npm/8.19.2 node/v18.10.0 darwin arm64 workspaces/false",
  "HOMEBREW_CELLAR": "/opt/homebrew/Cellar",
  "INFOPATH": "/opt/homebrew/share/info:/opt/homebrew/share/info:",
  "GIT_ASKPASS": "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh",
  "VSCODE_GIT_ASKPASS_NODE": "/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper",
  "COLORTERM": "truecolor",
  "npm_config_prefix": "/opt/homebrew",
  "npm_node_execpath": "/opt/homebrew/Cellar/node/18.10.0/bin/node",
  "RAPID_API_KEY": "0dbee03fcdmsh6f48b350984530ep1bbb64jsnbe01a4f5c863",
  "RAPID_API": "f9d2b7849amsh59ab96aaf4748b4p1f4facjsnf9a01b990b57"
};